hike/urls.py
from django.urls import path
from . import views

urlpatterns = [
  # home url
  path('', views.landing, name='landing'),

  # hike urls

  # show user selected hike ... needs id and user pk
  path('hike/<int:hike_id>', views.hike_detail, name='hike_detail'),

  #add a new hike
  path('hike/new', views.hike_new, name='hike_new'),

  path('hike/<int:pk>/edit', views.hike_edit, name='hike_edit'),

  # show hike calendar
  path('hike/calendar', views.hike_calendar, name='hike_calendar'),

  # add a comment to a hike
  path('hike/comment/<int:pk>', views.comment_new, name='comment_new'),

  # add user to hike
  path('hike/join/<int:pk>', views.hike_join, name='hike_join'),
]

hike_django/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from hike import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hike.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about, name='about'),
]

hike/models.py
from django.db import models
from accounts.models import Profile

# Create your models here.
class Hike(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='hike')
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    hike_date = models.DateField(null=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    zipcode = models.IntegerField(null=True)
    distance = models.FloatField(null=True)
    difficulty = models.FloatField(null=True)
    created_date = models.DateField(null=True)
    picture = models.TextField(null=True)

    def __str__(self):
        return self.title

        
class Comments(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='comment')
    hike = models.ForeignKey(Hike, on_delete=models.CASCADE, related_name='comment')
    body = models.CharField(max_length=250)
    rating = models.FloatField()

    def __str__(self):
        return self.body

class HikeGroup(models.Model):
    hike = models.ForeignKey(Hike, on_delete=models.CASCADE, related_name='hike_group')
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='hike_group')

    def __str__(self):
        return self.hike.title

hike/forms.py
from django import forms
from .models import Hike, Comments


#class DateInput(forms.DateInput):
 #   input_type = 'date'
 
class HikeForm(forms.ModelForm):

    class Meta:
        model = Hike
        #hike_date = forms.DateField(widget=DateInput()
       # widgets = {'hike_date' : DateInput()}
        fields = ('title', 'description', 'street', 'city', 'zipcode', 'hike_date', 'distance', 'picture', 'difficulty')

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ('body', 'rating')

hike/views.py
from django.shortcuts import render, redirect
from .models import Hike, Comments, HikeGroup
from accounts.models import Profile
from django.contrib.auth.decorators import login_required
from .forms import HikeForm, CommentForm

from django.contrib.auth.models import User
from accounts.models import Profile

# Create your views here.
# HIKE VIEWS

# landing page.
# Missing functionality - hike list and google calender
def landing(request):
  hikes = Hike.objects.all()
  if request.user.is_authenticated:
    user = request.user
    profile = Profile.objects.get(user=user.pk)
    return render(request, 'hike/landing.html', {'profile': profile,'hikes':hikes})
  else:
    return render(request, 'hike/landing.html', {'hikes':hikes})

# show user details about a selected hike.
# Missing functionality - selected hike with map)
def hike_detail(request, hike_id):
  hike = Hike.objects.get(id=hike_id)
  comments = Comments.objects.filter(hike=hike_id)
  hike_group = HikeGroup.objects.select_related('profile__user').filter(hike=hike_id)
  if request.user.is_authenticated:
    user = request.user
    profile = Profile.objects.get(user=user.pk)
    return render(request, 'hike/hike_detail.html', {'profile': profile,'hike':hike, 'comments': comments, 'user': user, 'hike_group': hike_group})
  else:
    return render(request, 'hike/hike_detail.html', {'hike':hike, 'hike_group': hike_group, 'comments': comments})

#add a new hike
# create a form to add a new hike

@login_required
def hike_new(request):
  user = request.user
  profile = Profile.objects.get(user=user.pk)
  if request.method == 'POST':
    form = HikeForm(request.POST)
    if form.is_valid():
      hike = form.save(commit=False)
      hike.profile = profile
      hike.save()
      return redirect('hike_detail', hike_id=hike.pk)
  else:
      form = HikeForm()
  return render(request, 'hike/hike_form.html', {'form': form, 'profile': profile})

@login_required
def hike_edit(request, pk):
    hike = Hike.objects.get(pk=pk)
    if request.method == 'POST':
        form = HikeForm(request.POST or None, instance=hike)
        # print("++++++++++IF POST++++++++++")
        if form.is_valid():
            form.save()
            # hike = form.save(commit=False)
            # print("++++++++++IF VALID++++++++++")
            # hike.save()
            return redirect('hike_detail')
    else:
        form = HikeForm(instance=Hike)
    print("++++++++++ELSE++++++++++")
    print("++++++++++RETURN++++++++++")
    return render(request, 'hike/hike_form.html', {'form': form, 'hike':hike})

# show all hikes on a calendar
def hike_calendar(request):
    hikes = Hike.objects.order_by('hike_date')
    if request.user.is_authenticated:
        user = request.user
        profile = Profile.objects.get(user=user.pk)
        return render(request, 'hike/hike_calendar.html', {'profile': profile, 'hikes': hikes})
    else:
        return render(request, 'hike/hike_calendar.html', {'hikes': hikes})

#add a comment
@login_required
def comment_new(request, pk):
    hike = Hike.objects.get(pk=pk)
    user = request.user
    profile = Profile.objects.get(user=user.pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
          comment = form.save(commit=False)
          comment.profile = profile
          comment.hike = hike
          comment.save()
          return redirect('hike_detail', hike_id=pk)
    else:
        form = CommentForm()
    return render(request, 'hike/comment_form.html', {'form': form, 'hike': hike, 'profile': profile})

def comment_detail(request, hike_id):
  comment = Comments.objects.get(id=hike_id)
  if request.user.is_authenticated:
    user = request.user
    profile = Profile.objects.get(id=user.pk)
    return render(request, 'hike/hike_detail.html', {'hike': hike,'comment':comment, 'profile': profile})
  else:
    return render(request, 'hike/hike_detail.html', {'hike':hike})

@login_required
def hike_join(request, pk):
   hike = Hike.objects.get(pk=pk)
   user = request.user
   profile = Profile.objects.get(user=user.pk)
   hikegroup = HikeGroup.objects.create(hike=hike, profile=profile)
   hikegroup.save()

   print(hikegroup.hike, "HikeGroup.hike")
   print(hikegroup.profile, "HikeGroup.profile")
   return redirect('hike_detail', hike_id=pk)

def about(request):
    if request.user.is_authenticated:
        user = request.user
        profile = Profile.objects.get(user=user.pk)
        return render(request, 'about.html', {'profile': profile})
    else:
        return render(request, 'about.html')

templates/hike/comment_form.html
{% extends 'base.html' %}
{% load static %}
{% block titleContent %}{{ hike.title }}{% endblock %}
{% block cssLink %}<link rel="stylesheet" href="{% static 'comment.css' %}" />
{% endblock %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	<!-- {{ form.as_p }} -->

	<div class="container">
		<h1>Add Comment</h1>
		<div class="commentForm">

			<label for="id_body">Body: </label>
			<input class="body" type="text" name="body" required style="height:160px" />

			<label for="id_rating">Rating: </label> 
			<input type="number" name="rating" step="any" required />
			<button type="submit" class="commentButton">Save</button>
		</div>
	</div>

</form>


{% endblock %}

templates/hike/hike_calendar.html
{% extends 'base.html' %}
{% load static %}
{% block titleContent %}Calendar{% endblock %}
{% block cssLink %}<link rel="stylesheet" href="{% static 'calendar.css' %}" />{% endblock %}

{% block content %}
<!-- link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" -->
<script>
  const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

  const dateToIdStr = (inp) => {
    return `${inp.getFullYear()}_${inp.getMonth() + 1}_${inp.getDate()}`;
  }

  const navigateCal = (e) => {
    if (e.path[1].dataset.date) {
      renderCal();
    } else {
      let navDate = new Date(e.path[2].dataset.date)
      if (e.path[0].className === 'js-cal-prev btn btn-default') {
        navDate.setMonth(navDate.getMonth()-1);
        renderCal(navDate);
      } else {
        navDate.setMonth(navDate.getMonth()+1);
        renderCal(navDate);
      }
    }
  }

  const renderCal = (date=new Date()) => {
    let month = date.getMonth(),
      year = date.getFullYear(),
      first = new Date(year, month, 1),
      last = new Date(year, month + 1, 0),
      startingDay = first.getDay(),
      thedate = new Date(year, month, 1 - startingDay),
      todayString = new Date().toDateString(),
      i, j;

      document.getElementById('moYr').innerText = `${months[month]} ${year}`;
      document.querySelector('.cal-nav').setAttribute('data-date', date.toDateString());

      let rows = '';
      for (j = 0; j < 6; j++) {
        rows += '<tr>';
        let cells = '';
        for (i = 0; i < 7; i++) {
          let dayClass = (thedate < first || thedate > last)? 'outside': 'current';
          let selected = (thedate.toDateString() === todayString)? 'selected': '';
          cells += `<td class="calendar-day ${selected} ${dayClass} js-cal-option" id="${dateToIdStr(thedate)}">
            <div class="date">${thedate.getDate()}</div>
          </td>`;
          thedate.setDate(thedate.getDate() + 1);
        }
        rows += `${cells} </tr>`;
      }
    document.getElementById('cal-content').innerHTML = rows;
    renderEvents();
  }

  const hikes = [{% for hike in hikes %}
    {
      hike_date: '{{hike.hike_date}}',
      hike_id: '{{hike.id}}',
      title: '{{hike.title}}',
      description: '{{hike.description}}',
      distance: '{{hike.distance}}',
      difficulty: '{{hike.difficulty}}'
    },
    {% endfor %}]


  const renderEvents = () => {
    hikes.forEach(hike => {
      let dayEl = document.getElementById(dateToIdStr(new Date(hike.hike_date)));
      if (dayEl) {
        let eventEl = document.createElement('div');
        eventEl.classList.add('event', 'begin', 'end');
        eventEl.setAttribute('title', hike.title);
        eventEl.innerHTML = `<a href="/hike/${hike.hike_id}">${hike.title}</a>`;
        dayEl.append(eventEl);
      }
    })
  }

</script>


    <table class="calendar-table table table-condensed table-tight">
      <thead>
        <tr>
          <td colspan="7" style="text-align: center; border-width:0">
            <table style="white-space: nowrap; width: 100%">
              <tr>
                <td class="cal-nav" style="text-align: left;">
                  <span class="btn-group">
                    <button class="js-cal-prev btn btn-default"><</button>
                    <button class="js-cal-next btn btn-default">></button>
                  </span>
                  <button class="js-cal-option btn btn-default">Today</button>
                </td>
                <td>
                  <span class="btn-group btn btn-group-lg" id="moYr">
                  </span>
                </td>
              </tr>
            </table>
            <thead>
              <tr class="c-weeks">
                  <th class="c-name">
                    Sunday
                  </th>
                  <th class="c-name">
                    Monday
                  </th>
                  <th class="c-name">
                    Tuesday
                  </th>
                  <th class="c-name">
                    Wednesday
                  </th>
                  <th class="c-name">
                    Thursday
                  </th>
                  <th class="c-name">
                    Friday
                  </th>
                  <th class="c-name">
                    Saturday
                  </th>
              </tr>
            </thead>
            <tbody id="cal-content">
            </tbody>
          </td>
        </tr>
      </thead>
    </table>
    <script>
      renderCal();
      document.querySelector('.js-cal-prev').addEventListener('click', navigateCal);
      document.querySelector('.js-cal-next').addEventListener('click', navigateCal);
      document.querySelector('.js-cal-option').addEventListener('click', navigateCal);
    </script>

    {% endblock %}

templates/hike/hike_detail.html
{% extends 'base.html' %}
{% load static %}
{% block titleContent %}{{ hike.title }}{% endblock %}
{% block cssLink %}<link rel="stylesheet" href="{% static 'hike_detail.css' %}" />{% endblock %}
{% block scripts %}
<script>
function initMap() {
    // The location of Uluru
	var uluru = {lat: {{ hike.latitude}}, lng: {{hike.longitude}}};
    // The map, centered at Uluru
    var map = new google.maps.Map(
		document.getElementById('map'), {zoom: 15, center: uluru});
    // The marker, positioned at Uluru
    var marker = new google.maps.Marker({position: uluru, map: map});
}
</script>
<!-- https://maps.googleapis.com/maps/api/geocode/xml?address={{ hike.street }},+CA&key=AIzaSyBHLett8djBo62dDXj0EjCimF8Rd6E8cxg&callback=initMap -->
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHLett8djBo62dDXj0EjCimF8Rd6E8cxg&callback=initMap"></script>
{% endblock %}
{% block content %}


<div class="main">
	<img src="{{ hike.picture }}" alt="hike-photo" >

	<h1>{{ hike.title }}</h1>
	<p style="text-align: center"><b>Distance:</b> {{ hike.distance }} - <b>Difficulty:</b> {{ hike.difficulty }}</p>

	<p>{{ hike.description }}</p>
</div>

<div class="comments">
	<h4>Comments:</a></h4>
	<ul>
		{% for comment in comments %}
		<li class="comment">
			<span class="username">{{ user.username }}:</span> {{ comment.body }}
		</li>
		{% endfor %}
	</ul>
	<a href="{% url 'comment_new' pk=hike.pk %}">(+) Comment</a>

</div>
<div class="joinUs">
		<h4>Who's going:</h4>
		* {% for hiker in hike_group %}
			{{hiker.profile.user.username}} *
		{% endfor %}<br/>
		<a href="{% url 'hike_join' pk=hike.pk %}">(+) Join this hike</a>

</div>



	<!-- Google  Map -->
	<!--The div element for the map -->
	<div>
		<p style="text-align: center"><b>Address: </b>{{ hike.street }} - {{ hike.city }} - {{ hike.zipcode }}</p>
	</div>
	<div id="map"></div>


{% endblock %}

templates/hike/hike_form.html
{% extends 'base.html' %} 
{% load static %}
{% block titleContent %}Add or Update your hike{% endblock %}
{% block cssLink %}<link rel="stylesheet" href="{% static 'hikeform.css' %}" />
{% endblock %}

{% block content %}

	<form method="POST">
		{% csrf_token %}
		<!-- {{ form.as_p }} -->
		<div class="container">
				<h1>Add A New Hike</h1>
				<div class="hikeForm">
				<label for="title">Title: </label>
				<input class="title" type="text" name="title" required value="{{hike.title}}" />

				<label for="description">Description: </label>
				<input class="description" type="text" name="description" style="height:160px" required value="{{hike.description}}" />

				<label for="street">Street: </label>
				<input class="street" type="text" name="street" required value="{{hike.street}}" />

				<label for="city">City: </label>
				<input class="city" type="text" name="city" required value="{{hike.city}}" />

				<label for="zipcode">Zip Code: </label>
				<input class="zipcode" type="number" name="zipcode" required value="{{hike.zipcode}}" />

				<label for="picture">Picture </label>
				<input class="picture" type="text" name="picture" required value="{{hike.picture}}" />

				<label for="hike_date">Hike Date: </label>
				<input class="hike_date" type="date" name="hike_date" required value="{{hike.hike_date}}" />

				<label for="distance">Distance: </label>
				<input class="distance" type="number" name="distance" required value="{{hike.distance}}" />

				<label for="difficulty">Difficulty: </label>
				<input class="difficulty" type="number" name="difficulty" required value="{{hike.difficulty}}" />

				<label for="longitude">Longitude: </label>
				<input class="longitude" type="number" name="longitude" />

				<label for="latitude">Latitude: </label>
				<input class="latitude" type="number" name="latitude" />


			</div>
				<p>By adding a hike you agree to our <b>Terms & Conditions</b></p>
		
				<button type="submit" class="hikeButton">Save</button>
			</div>
						
	</form>
{% endblock %}

templates/hike/hike_new.html
{% extends 'base.html' %}
{% load static %}
{% block titleContent %}Add or Update your hike{% endblock %}
{% block cssLink %}{% endblock %}
{% block content %}
<h1>Add / Edit / Update Hike</h1>


{% endblock %}

templates/hike/landing.html
{% extends 'base.html' %}

{% load static %}

{% block titleContent %}Welcome{% endblock %}

{% block cssLink %}<link rel="stylesheet" href="{% static 'landing_page.css' %}" />
{% endblock %}

{% block content %}


<!-- hero -->

<div class="main-landing">
    <img  src="/static/image/hiker-group.jpg" alt="hiker-group" >
    <h1>Welcome to Happy Hiking</h1>

    <p>

    Why do we use it?
    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

    </p>
    </div>



    <!-- upcomming -->
    <div class="content">
      <h2 id="hikelist">Upcoming hikes</h2>

      <div class="ban-bottom-w3l">
          <div class="row grid-divider col1">
            {% for hike in hikes|slice:":3" %}
            <div class="col-sm-4">
              <div class="col-padding">
                <img class="img-responsive" src="{{ hike.picture }}" alt="hike-photo" > <br>
                <h3><a href="{% url 'hike_detail' hike_id=hike.id %}">{{ hike.title }}</a></h3>
            <ul>
            <li><strong> Day: </strong>  {{hike.hike_date}}</li>
            <li class="limit"><strong> Description : </strong> {{hike.description|truncatewords:60}}</li>
            <li><br/><strong> Difficulty: </strong> {{hike.difficulty}}</li>
            <li><strong> Distance: </strong> {{hike.distance}} miles</li>
            </ul>
              </div>
            </div>
            {% endfor %}

        </div>
      </div>
    </div>



{% endblock %}